[package]
name = "glyph"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
glam = "0.32.0"
lazy_static = "1.5.0"
num-traits = "0.2.19"
parking_lot = "0.12.5"
ratatui = "0.30.0"
